# Generated by Django 2.1.10 on 2020-05-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usernotificationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationhistory',
            old_name='attachment',
            new_name='email_attachment',
        ),
    ]
