# Generated by Django 2.1.10 on 2020-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20200516_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogquestion',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
