# Generated by Django 2.1.10 on 2020-05-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_useractivity_referrer_asked_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
